In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('./Source Files/monsters.csv')
pd.set_option('display.max_columns', None)
df.head()

,Unnamed: 0,_id,index,name,size,type,subtype,alignment,armor_class,hit_points,hit_dice,speed,strength,dexterity,constitution,intelligence,wisdom,charisma,proficiencies,damage_vulnerabilities,damage_resistances,damage_immunities,condition_immunities,senses,languages,challenge_rating,special_abilities,actions,legendary_actions,url,reactions,other_speeds
0,0,5f2329ad0b1bb138c59411ee,aboleth,Aboleth,Large,aberration,NaN,lawful evil,17,135,18d10,"{'walk': '10 ft.', 'swim': '40 ft.'}",21,9,15,18,15,18,"[{'name': 'Saving Throw: CON', 'url': '/api/pr...",[],[],[],[],"{'darkvision': '120 ft.', 'passive_perception'...","Deep Speech, telepathy 120 ft.",10.00,"[{'name': 'Amphibious', 'desc': 'The aboleth c...","[{'name': 'Multiattack', 'desc': 'The aboleth ...","[{'name': 'Detect', 'desc': 'The aboleth makes...",/api/monsters/aboleth,NaN,NaN
1,1,5f2329ad0b1bb138c59411ef,acolyte,Acolyte,Medium,humanoid,any race,any alignment,10,9,2d8,{'walk': '30 ft.'},10,10,10,10,14,11,"[{'name': 'Skill: Medicine', 'url': '/api/prof...",[],[],[],[],{'passive_perception': 12},any one language (usually Common),0.25,"[{'name': 'Spellcasting', 'desc': 'The acolyte...","[{'name': 'Club', 'desc': 'Melee Weapon Attack...",NaN,/api/monsters/acolyte,NaN,NaN
2,2,5f2329ad0b1bb138c59411f1,adult-black-dragon,Adult Black Dragon,Huge,dragon,NaN,chaotic evil,19,195,17d12,"{'walk': '40 ft.', 'fly': '80 ft.', 'swim': '4...",23,14,21,14,13,17,"[{'name': 'Saving Throw: DEX', 'url': '/api/pr...",[],[],['acid'],[],"{'blindsight': '60 ft.', 'darkvision': '120 ft...","Common, Draconic",14.00,"[{'name': 'Amphibious', 'desc': 'The dragon ca...","[{'name': 'Multiattack', 'desc': 'The dragon c...","[{'name': 'Detect', 'desc': 'The dragon makes ...",/api/monsters/adult-black-dragon,NaN,NaN
3,3,5f2329ad0b1bb138c59411f0,adult-blue-dragon,Adult Blue Dragon,Huge,dragon,NaN,lawful evil,19,225,18d12,"{'walk': '40 ft.', 'burrow': '30 ft.', 'fly': ...",25,10,23,16,15,19,"[{'name': 'Saving Throw: DEX', 'url': '/api/pr...",[],[],['lightning'],[],"{'blindsight': '60 ft.', 'darkvision': '120 ft...","Common, Draconic",16.00,"[{'name': 'Legendary Resistance', 'desc': 'If ...","[{'name': 'Multiattack', 'desc': 'The dragon c...","[{'name': 'Detect', 'desc': 'The dragon makes ...",/api/monsters/adult-blue-dragon,NaN,NaN
4,4,5f2329ad0b1bb138c59411f2,adult-brass-dragon,Adult Brass Dragon,Huge,dragon,NaN,chaotic good,18,172,15d12,"{'walk': '40 ft.', 'burrow': '40 ft.', 'fly': ...",23,10,21,14,13,17,"[{'name': 'Saving Throw: DEX', 'url': '/api/pr...",[],[],['fire'],[],"{'blindsight': '60 ft.', 'darkvision': '120 ft...","Common, Draconic",13.00,"[{'name': 'Legendary Resistance', 'desc': 'If ...","[{'name': 'Multiattack', 'desc': 'The dragon c...",NaN,/api/monsters/adult-brass-dragon,NaN,NaN

In [3]:
df.shape

(322, 32)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 322 entries, 0 to 321
Data columns (total 32 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              322 non-null    int64
 1   _id                     322 non-null    object
 2   index                   322 non-null    object
 3   name                    322 non-null    object
 4   size                    322 non-null    object
 5   type                    322 non-null    object
 6   subtype                 64 non-null     object
 7   alignment               322 non-null    object
 8   armor_class             322 non-null    int64
 9   hit_points              322 non-null    int64
 10  hit_dice                322 non-null    object
 11  speed                   322 non-null    object
 12  strength                322 non-null    int64
 13  dexterity               322 non-null    int64
 14  constitution            322 non-null    int64
 15  intelligence            322 non-null    int64
 16  wisdom                  322 non-null    int64
 17  charisma                322 non-null    int64
 18  proficiencies           322 non-null    object
 19  damage_vulnerabilities  322 non-null    object
 20  damage_resistances      322 non-null    object
 21  damage_immunities       322 non-null    object
 22  condition_immunities    322 non-null    object
 23  senses                  322 non-null    object
 24  languages               193 non-null    object
 25  challenge_rating        322 non-null    float64
 26  special_abilities       266 non-null    object
 27  actions                 320 non-null    object
 28  legendary_actions       29 non-null     object
 29  url                     322 non-null    object
 30  reactions               11 non-null     object
 31  other_speeds            4 non-null      object
dtypes: float64(1), int64(9), object(22)
memory usage: 80.6+ KB

In [5]:
# removing redundant variables and datapoints with no combatative use (languages)
df = df[['name', 'size', 'type', 'alignment', 'armor_class', 'hit_points', 'hit_dice', 'speed',
       'strength', 'dexterity', 'constitution', 'intelligence', 'wisdom',
       'charisma', 'proficiencies', 'damage_vulnerabilities',
       'damage_resistances', 'damage_immunities', 'condition_immunities',
       'senses', 'challenge_rating', 'special_abilities',
       'actions', 'legendary_actions', 'reactions', 'other_speeds']]
df.replace('[]', np.nan, inplace=True)
df.head()

,name,size,type,alignment,armor_class,hit_points,hit_dice,speed,strength,dexterity,constitution,intelligence,wisdom,charisma,proficiencies,damage_vulnerabilities,damage_resistances,damage_immunities,condition_immunities,senses,challenge_rating,special_abilities,actions,legendary_actions,reactions,other_speeds
0,Aboleth,Large,aberration,lawful evil,17,135,18d10,"{'walk': '10 ft.', 'swim': '40 ft.'}",21,9,15,18,15,18,"[{'name': 'Saving Throw: CON', 'url': '/api/pr...",NaN,NaN,NaN,NaN,"{'darkvision': '120 ft.', 'passive_perception'...",10.00,"[{'name': 'Amphibious', 'desc': 'The aboleth c...","[{'name': 'Multiattack', 'desc': 'The aboleth ...","[{'name': 'Detect', 'desc': 'The aboleth makes...",NaN,NaN
1,Acolyte,Medium,humanoid,any alignment,10,9,2d8,{'walk': '30 ft.'},10,10,10,10,14,11,"[{'name': 'Skill: Medicine', 'url': '/api/prof...",NaN,NaN,NaN,NaN,{'passive_perception': 12},0.25,"[{'name': 'Spellcasting', 'desc': 'The acolyte...","[{'name': 'Club', 'desc': 'Melee Weapon Attack...",NaN,NaN,NaN
2,Adult Black Dragon,Huge,dragon,chaotic evil,19,195,17d12,"{'walk': '40 ft.', 'fly': '80 ft.', 'swim': '4...",23,14,21,14,13,17,"[{'name': 'Saving Throw: DEX', 'url': '/api/pr...",NaN,NaN,['acid'],NaN,"{'blindsight': '60 ft.', 'darkvision': '120 ft...",14.00,"[{'name': 'Amphibious', 'desc': 'The dragon ca...","[{'name': 'Multiattack', 'desc': 'The dragon c...","[{'name': 'Detect', 'desc': 'The dragon makes ...",NaN,NaN
3,Adult Blue Dragon,Huge,dragon,lawful evil,19,225,18d12,"{'walk': '40 ft.', 'burrow': '30 ft.', 'fly': ...",25,10,23,16,15,19,"[{'name': 'Saving Throw: DEX', 'url': '/api/pr...",NaN,NaN,['lightning'],NaN,"{'blindsight': '60 ft.', 'darkvision': '120 ft...",16.00,"[{'name': 'Legendary Resistance', 'desc': 'If ...","[{'name': 'Multiattack', 'desc': 'The dragon c...","[{'name': 'Detect', 'desc': 'The dragon makes ...",NaN,NaN
4,Adult Brass Dragon,Huge,dragon,chaotic good,18,172,15d12,"{'walk': '40 ft.', 'burrow': '40 ft.', 'fly': ...",23,10,21,14,13,17,"[{'name': 'Saving Throw: DEX', 'url': '/api/pr...",NaN,NaN,['fire'],NaN,"{'blindsight': '60 ft.', 'darkvision': '120 ft...",13.00,"[{'name': 'Legendary Resistance', 'desc': 'If ...","[{'name': 'Multiattack', 'desc': 'The dragon c...",NaN,NaN,NaN

In [6]:
df.isna().sum()

name                        0
size                        0
type                        0
alignment                   0
armor_class                 0
hit_points                  0
hit_dice                    0
speed                       0
strength                    0
dexterity                   0
constitution                0
intelligence                0
wisdom                      0
charisma                    0
proficiencies             109
damage_vulnerabilities    307
damage_resistances        256
damage_immunities         199
condition_immunities      230
senses                      0
challenge_rating            0
special_abilities          56
actions                     2
legendary_actions         293
reactions                 311
other_speeds              318
dtype: int64

# API Stripping 
Columns which need stripping
- "speed"
- "proficiencies"
- "damage_vulnerabilities"
- "damage_resistances"
- "damage_immunities"
- "condition_immunities"
- "senses"
- "special_abilities"
- "actions"
- "legendary_actions"
- "reactions"
- "other_speeds"

In [ ]:
data = pd.DataFrame(df["speed"].value_counts())
# pd.set_option('display.max_rows', None)   // For showing all data forms
data

                                                    count
speed
{'walk': '30 ft.'}                                     68
{'walk': '40 ft.'}                                     40
{'walk': '50 ft.'}                                     16
{'walk': '40 ft.', 'fly': '80 ft.', 'swim': '40...     12
{'walk': '30 ft.', 'swim': '30 ft.'}                   10
...                                                   ...
{'walk': '20 ft.', 'fly': '60 ft.'}                     1
{'walk': '50 ft.', 'fly': '50 ft.', 'hover': True}      1
{'swim': '60 ft.'}                                      1
{'walk': '20 ft.', 'swim': '60 ft.'}                    1
{'walk': '40 ft.', 'burrow': '20 ft.', 'fly': '...      1

[85 rows x 1 columns]

In [10]:
df["speed"] = df["speed"].str.replace("{", '')
df["speed"] = df["speed"].str.replace("}", '')
df["speed"] = df["speed"].str.replace("'", '')
df["speed"] = df["speed"].str.replace(",", ' |')
df["speed"] = df["speed"].str.replace("walk", 'Walk')
df["speed"] = df["speed"].str.replace("fly", 'Fly')
df["speed"] = df["speed"].str.replace("swim", 'Swim')
df["speed"] = df["speed"].str.replace("climb", 'Climb')
df["speed"] = df["speed"].str.replace("hover", 'Hover')
df["speed"] = df["speed"].str.replace("burrow", 'Burrow')
data = pd.DataFrame(df["speed"].unique())
data

                                                    0
0                         Walk: 10 ft. | Swim: 40 ft.
1                                        Walk: 30 ft.
2           Walk: 40 ft. | Fly: 80 ft. | Swim: 40 ft.
3         Walk: 40 ft. | Burrow: 30 ft. | Fly: 80 ft.
4         Walk: 40 ft. | Burrow: 40 ft. | Fly: 80 ft.
..                                                ...
80            Walk: 0 ft. | Fly: 60 ft. | Hover: True
81                         Walk: 20 ft. | Fly: 80 ft.
82                      Walk: 20 ft. | Burrow: 20 ft.
83        Walk: 40 ft. | Burrow: 20 ft. | Fly: 80 ft.
84  Walk: 40 ft. | Burrow: 20 ft. | Fly: 80 ft. | ...

[85 rows x 1 columns]

In [11]:
data = pd.DataFrame(df["proficiencies"].value_counts())
# pd.set_option('display.max_rows', None)   // For showing all data forms
data

                                                    count
proficiencies
nan                                                   109
[{'name': 'Skill: Perception', 'url': '/api/pro...     12
[{'name': 'Skill: Perception', 'url': '/api/pro...     12
[{'name': 'Skill: Perception', 'url': '/api/pro...      9
[{'name': 'Skill: Perception', 'url': '/api/pro...      6
...                                                   ...
[{'name': 'Skill: Perception', 'url': '/api/pro...      1
[{'name': 'Saving Throw: CON', 'url': '/api/pro...      1
[{'name': 'Skill: Athletics', 'url': '/api/prof...      1
[{'name': 'Skill: Stealth', 'url': '/api/profic...      1
[{'name': 'Saving Throw: DEX', 'url': '/api/pro...      1

[147 rows x 1 columns]

In [12]:
df["proficiencies"] = df["proficiencies"].str.replace("[", '')
df["proficiencies"] = df["proficiencies"].str.replace("]", '')
df["proficiencies"] = df["proficiencies"].str.replace("{", '')
df["proficiencies"] = df["proficiencies"].str.replace("}", '')
df["proficiencies"] = df["proficiencies"].str.replace("',", ' ')
df["proficiencies"] = df["proficiencies"].str.replace("'", ' ')
df["proficiencies"] = df["proficiencies"].str.replace(",", ' |')
df["proficiencies"] = df["proficiencies"].str.title()
df["proficiencies"] = df["proficiencies"].str.replace("Url :", '')
df["proficiencies"] = df["proficiencies"].str.replace("Name : ", '')
df["proficiencies"] = df["proficiencies"].str.replace("Value : ", '+')
df["proficiencies"] = df["proficiencies"].str.replace("/Api/Proficiencies/", '')
data = pd.DataFrame(df["proficiencies"].value_counts())
data

                                                    count
proficiencies
Nan                                                   109
  Skill: Perception     Skill-Perception   +4          12
  Skill: Perception     Skill-Perception   +3          12
  Skill: Perception     Skill-Perception   +2           9
  Skill: Perception     Skill-Perception   +3 |...      6
...                                                   ...
  Skill: Perception     Skill-Perception   +8           1
  Saving Throw: Con     Saving-Throw-Con   +7 |...      1
  Skill: Athletics     Skill-Athletics   +6 |  ...      1
  Skill: Stealth     Skill-Stealth   +6 |   Ski...      1
  Saving Throw: Dex     Saving-Throw-Dex   +3 |...      1

[147 rows x 1 columns]

In [ ]:
data = pd.DataFrame(df["speed"].value_counts())
# pd.set_option('display.max_rows', None)   // For showing all data forms
data

In [14]:
data = pd.DataFrame(df["other_speeds"].value_counts())
# pd.set_option('display.max_rows', None)
data

                                                    count
other_speeds
[{'form': 'hyrid', 'speed': {'walk': '40 ft.', ...      1
[{'form': 'boar', 'speed': {'walk': '40 ft.'}}]         1
[{'form': 'tiger', 'speed': {'walk': '40 ft.'}}]        1
[{'form': 'wolf', 'speed': {'walk': '40 ft.'}}]         1

In [15]:
df["other_speeds"] = df["other_speeds"].str.replace("{", '')
df["other_speeds"] = df["other_speeds"].str.replace("}},", ' |')
df["other_speeds"] = df["other_speeds"].str.replace("[", '')
df["other_speeds"] = df["other_speeds"].str.replace("]", '')
df["other_speeds"] = df["other_speeds"].str.replace("}", '')
df["other_speeds"] = df["other_speeds"].str.replace("'", '')
df["other_speeds"] = df["other_speeds"].str.replace(",", '')
df["other_speeds"] = df["other_speeds"].str.replace("walk", 'Walk')
df["other_speeds"] = df["other_speeds"].str.replace("climb", 'Climb')
df["other_speeds"] = df["other_speeds"].str.replace("form: hyrid", 'Hybrid')
df["other_speeds"] = df["other_speeds"].str.replace("form: bear", 'Bear')
df["other_speeds"] = df["other_speeds"].str.replace("form: boar", 'Boar')
df["other_speeds"] = df["other_speeds"].str.replace("form: tiger", 'Tiger')
df["other_speeds"] = df["other_speeds"].str.replace("form: wolf", 'Wolf')
df["other_speeds"] = df["other_speeds"].str.replace("speed", 'Speeds')
data = pd.DataFrame(df["other_speeds"].value_counts())
data

                                                    count
other_speeds
Hybrid Speeds: Walk: 40 ft. Climb: 30 ft. | Bea...      1
Boar Speeds: Walk: 40 ft.                               1
Tiger Speeds: Walk: 40 ft.                              1
Wolf Speeds: Walk: 40 ft.                               1